### ISSUE TITLE
Inkdrop new version 

### ISSUE THREAD

**Issue by erdemalpkaya** [libeanim/inkdrop-admonition#1]
Hi, your application is not working with v.4 of Inkdrop

**Comment by e-stokes** [comment]
I would also like to know if this works on the Mac? Or is it just the version of Inkdrop that causes it not to work?

**Comment by erdemalpkaya** [comment]
> I would also like to know if this works on the Mac? Or is it just the version of Inkdrop that causes it not to work?

Hi @e-stokes Yes I used with V.3 version and it is a great plugins. The only problem is the version of the Inkdrop that affect mostly plugins.

**Comment by e-stokes** [comment]
Hi @erdemalpkaya, Thank you for the reply. The plugin looks great and helpful, only wish it worked with the current version. Hopefully it will soon.

**Comment by e-stokes** [comment]
I would like to update that quitting and restarting Inkdrop seemed to fix the issues for me. Hope this will help anyone else. Restart Inkdrop after Terminal install.

**Comment by erdemalpkaya** [comment]
> I would like to update that quitting and restarting Inkdrop seemed to fix the issues for me. Hope this will help anyone else. Restart Inkdrop after Terminal install.

Hi @e-stokes Are you using V.4 Inkdrop? (beta-version). Normally you cannot be able to install the plugins if you are using V.4 version Inkdrop.

**Comment by e-stokes** [comment]
@erdemalpkaya Ah I see! Sorry I misunderstood, I'm not running the beta version. Thank you for clarifying 👍🏻

**Comment by craftzdog** [comment]
Hi, I'm the developer of Inkdrop.
I wrote [a plugin migration guide for v4](https://beta.docs.inkdrop.app/manual/plugin-migration-from-v3-to-v4), please check it out!
The v4 will be rolled out soon.
Thanks for your great plugin!

Cheers

**Comment by libeanim** [comment]
@erdemalpkaya can you test if it the updated version now works with inkdrop v4? thx.

**Comment by nicpitsch** [comment]
I get an error on starting Inkdrop. A popup on the right-side within Inkdrop indicates *...osal-object-rest-spread' from 'D:\Data\Programme\Inkdrop\program'*. 

The Inkdrop Developer Tools console contains `app:error Notification: Failed to load the admonition package.
Object detail: "Cannot find module '@babel/plugin-proposal-object-rest-spread' from 'D:\Data\Programme\Inkdrop\program'" 
dismissable:true
packageName: "admonition"
stack: "Error: Cannot find module '@babel/plugin-proposal-object-rest-spread' from 'D:\Data\Programme\Inkdrop\program'.`.... and much more content.

*D:\Data\Programme\Inkdrop\program* is the installation directory of Inkdrop, version 4.0.0-beta.8, zip-Archive variant.

**Comment by erdemalpkaya** [comment]
> @erdemalpkaya can you test if it the updated version now works with inkdrop v4? thx.

Thank you for update @libeanim but I am getting babel package error.

**Comment by craftzdog** [comment]
Oops, it's the app's fault. On it.

**Comment by craftzdog** [comment]
It should work with v4.0.0-beta.9!

**Comment by erdemalpkaya** [comment]
Thank you @libeanim and @craftzdog.

The plugin is working well on v.4 now. Thanks
